/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fabrica.de.projetos;

/**
 *
 * @author gabri
 */
public class RemedioTela extends javax.swing.JFrame {

    /**
     * Creates new form RemedioTela
     */
    public RemedioTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextField4 = new javax.swing.JTextField();
        txt_cpf7 = new javax.swing.JTextField();
        txt_cpf2 = new javax.swing.JTextField();
        txt_cpf5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel2 = new java.awt.Panel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        Tipo1 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        panel3 = new java.awt.Panel();
        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        txt_cpf4 = new javax.swing.JTextField();
        txt_cpf6 = new javax.swing.JTextField();
        txt_cpf8 = new javax.swing.JTextField();
        txt_cpf9 = new javax.swing.JTextField();
        btn_confirmar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField4.setText("jTextField4");

        txt_cpf7.setBackground(new java.awt.Color(224, 229, 243));
        txt_cpf7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txt_cpf7.setCaretColor(new java.awt.Color(38, 53, 99));
        txt_cpf7.setSelectionColor(new java.awt.Color(38, 53, 99));
        txt_cpf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpf7ActionPerformed(evt);
            }
        });

        txt_cpf2.setBackground(new java.awt.Color(224, 229, 243));
        txt_cpf2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txt_cpf2.setCaretColor(new java.awt.Color(38, 53, 99));
        txt_cpf2.setSelectionColor(new java.awt.Color(38, 53, 99));
        txt_cpf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpf2ActionPerformed(evt);
            }
        });

        txt_cpf5.setBackground(new java.awt.Color(224, 229, 243));
        txt_cpf5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txt_cpf5.setCaretColor(new java.awt.Color(38, 53, 99));
        txt_cpf5.setSelectionColor(new java.awt.Color(38, 53, 99));
        txt_cpf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpf5ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        panel2.setLayout(null);

        jLabel8.setText("Nome\n");
        panel2.add(jLabel8);
        jLabel8.setBounds(100, 60, 37, 16);

        jTextField6.setText("jTextField1");
        panel2.add(jTextField6);
        jTextField6.setBounds(140, 60, 71, 22);

        jLabel9.setText("Fornecedor\n");
        panel2.add(jLabel9);
        jLabel9.setBounds(100, 110, 60, 16);

        jTextField7.setText("jTextField2");
        panel2.add(jTextField7);
        jTextField7.setBounds(170, 110, 71, 22);

        jLabel10.setText("Preço");
        panel2.add(jLabel10);
        jLabel10.setBounds(100, 160, 37, 16);

        jTextField8.setText("jTextField3");
        panel2.add(jTextField8);
        jTextField8.setBounds(140, 160, 71, 22);

        jLabel11.setText("Tarja");
        panel2.add(jLabel11);
        jLabel11.setBounds(320, 60, 30, 16);

        jLabel12.setText("Peso Líquido");
        panel2.add(jLabel12);
        jLabel12.setBounds(320, 110, 68, 16);

        jTextField9.setText("jTextField5");
        panel2.add(jTextField9);
        jTextField9.setBounds(390, 110, 71, 22);

        Tipo1.setText("Tipo");
        panel2.add(Tipo1);
        Tipo1.setBounds(320, 160, 30, 16);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comprimido", "Gota" }));
        panel2.add(jComboBox3);
        jComboBox3.setBounds(350, 160, 120, 22);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "Vermelha", "Preta" }));
        panel2.add(jComboBox4);
        jComboBox4.setBounds(350, 60, 84, 22);

        jTabbedPane1.addTab("Cadastro", panel2);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", panel3);

        panel1.setLayout(null);

        jLabel3.setText("Nome\n");
        panel1.add(jLabel3);
        jLabel3.setBounds(60, 40, 37, 16);

        jLabel4.setText("Fornecedor\n");
        panel1.add(jLabel4);
        jLabel4.setBounds(60, 120, 60, 16);

        jLabel5.setText("Preço");
        panel1.add(jLabel5);
        jLabel5.setBounds(60, 200, 37, 16);

        jLabel6.setText("Tarja");
        panel1.add(jLabel6);
        jLabel6.setBounds(320, 40, 30, 16);

        jLabel7.setText("Peso Líquido");
        panel1.add(jLabel7);
        jLabel7.setBounds(320, 120, 68, 16);

        Tipo.setText("Tipo");
        panel1.add(Tipo);
        Tipo.setBounds(320, 200, 30, 16);

        jComboBox1.setBackground(new java.awt.Color(224, 229, 243));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comprimido", "Gota" }));
        panel1.add(jComboBox1);
        jComboBox1.setBounds(360, 190, 180, 30);

        jComboBox2.setBackground(new java.awt.Color(224, 229, 243));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "Vermelha", "Preta" }));
        panel1.add(jComboBox2);
        jComboBox2.setBounds(380, 30, 160, 30);

        txt_cpf4.setBackground(new java.awt.Color(224, 229, 243));
        txt_cpf4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txt_cpf4.setCaretColor(new java.awt.Color(38, 53, 99));
        txt_cpf4.setSelectionColor(new java.awt.Color(38, 53, 99));
        txt_cpf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpf4ActionPerformed(evt);
            }
        });
        panel1.add(txt_cpf4);
        txt_cpf4.setBounds(130, 110, 140, 30);

        txt_cpf6.setBackground(new java.awt.Color(224, 229, 243));
        txt_cpf6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txt_cpf6.setCaretColor(new java.awt.Color(38, 53, 99));
        txt_cpf6.setSelectionColor(new java.awt.Color(38, 53, 99));
        txt_cpf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpf6ActionPerformed(evt);
            }
        });
        panel1.add(txt_cpf6);
        txt_cpf6.setBounds(100, 190, 170, 30);

        txt_cpf8.setBackground(new java.awt.Color(224, 229, 243));
        txt_cpf8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txt_cpf8.setCaretColor(new java.awt.Color(38, 53, 99));
        txt_cpf8.setSelectionColor(new java.awt.Color(38, 53, 99));
        txt_cpf8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpf8ActionPerformed(evt);
            }
        });
        panel1.add(txt_cpf8);
        txt_cpf8.setBounds(100, 30, 170, 30);

        txt_cpf9.setBackground(new java.awt.Color(224, 229, 243));
        txt_cpf9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txt_cpf9.setCaretColor(new java.awt.Color(38, 53, 99));
        txt_cpf9.setSelectionColor(new java.awt.Color(38, 53, 99));
        txt_cpf9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpf9ActionPerformed(evt);
            }
        });
        panel1.add(txt_cpf9);
        txt_cpf9.setBounds(400, 110, 140, 30);

        btn_confirmar.setBackground(new java.awt.Color(38, 53, 99));
        btn_confirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_confirmar.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirmar.setText("confirmar");
        panel1.add(btn_confirmar);
        btn_confirmar.setBounds(460, 250, 110, 30);

        jTabbedPane1.addTab("Consulta", panel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cpf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpf2ActionPerformed

    private void txt_cpf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpf4ActionPerformed

    private void txt_cpf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpf5ActionPerformed

    private void txt_cpf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpf6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpf6ActionPerformed

    private void txt_cpf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpf7ActionPerformed

    private void txt_cpf8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpf8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpf8ActionPerformed

    private void txt_cpf9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpf9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpf9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemedioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemedioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemedioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemedioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemedioTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel Tipo1;
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JTextField txt_cpf2;
    private javax.swing.JTextField txt_cpf4;
    private javax.swing.JTextField txt_cpf5;
    private javax.swing.JTextField txt_cpf6;
    private javax.swing.JTextField txt_cpf7;
    private javax.swing.JTextField txt_cpf8;
    private javax.swing.JTextField txt_cpf9;
    // End of variables declaration//GEN-END:variables
}
