/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fabrica.de.projetos;

import conexao.MySQL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import objetos.Medicamentos;

/**
 *
 * @author gabri
 */
public class ResultadoRemedio extends javax.swing.JFrame {

    /**
     * Creates new form ResultadoRemédio
     */
    public ResultadoRemedio() {
        initComponents();
        gettingListOfFrn();
        popularComboBox();
    }
    
    MySQL conectar = new MySQL("localhost:3306","DataFarmaBanco","root","123mudar");
    ArrayList<String> listaForn = new ArrayList<String>();
    
    
    private void popularComboBox() {
        for (int i = 0; i < this.listaForn.size(); i++) {
            comboEditMedcForn.addItem(this.listaForn.get(i));
        }
    }
    
    private void gettingListOfFrn() {
        this.conectar.conectaBanco();
        try {
            this.conectar.executarSQL("SELECT nome from fornecedores");
            while(this.conectar.getResultSet().next()){
                this.listaForn.add(this.conectar.getResultSet().getString(1));
            }
        } catch (Exception e) {
            System.out.println(e);
        } finally {
            this.conectar.conectaBanco();
        }
    }
    
    public void setNovoRemedio(Medicamentos novoMedicamento) {
        txtEditMedcNome.setText(novoMedicamento.getNome());
        txtEditMedcPeso.setText(String.valueOf(novoMedicamento.getPeso()));
        txtEditMedcPreco.setText(String.valueOf(novoMedicamento.getPreco()));
        txtEditMedcQtd.setText(String.valueOf(novoMedicamento.getQtd_estoque()));
        comboEditMedcForn.setSelectedIndex(novoMedicamento.getFornecedorId() - 1);
        comboEditMedcTarja.setSelectedItem(novoMedicamento.getTarja());
        comboEditMedcTipo.setSelectedItem(novoMedicamento.getTipo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bntApagarMedicamento = new javax.swing.JButton();
        btn_confirmar2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Tipo2 = new javax.swing.JLabel();
        comboEditMedcTipo = new javax.swing.JComboBox<>();
        comboEditMedcForn = new javax.swing.JComboBox<>();
        txtEditMedcPreco = new javax.swing.JTextField();
        txtEditMedcNome = new javax.swing.JTextField();
        txtEditMedcPeso = new javax.swing.JTextField();
        comboEditMedcTarja = new javax.swing.JComboBox<>();
        txtEditMedcQtd = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Resultado");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 100, 28);

        bntApagarMedicamento.setBackground(new java.awt.Color(255, 51, 51));
        bntApagarMedicamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntApagarMedicamento.setForeground(new java.awt.Color(255, 255, 255));
        bntApagarMedicamento.setText("remover remédio");
        bntApagarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntApagarMedicamentoActionPerformed(evt);
            }
        });
        jPanel1.add(bntApagarMedicamento);
        bntApagarMedicamento.setBounds(40, 270, 230, 30);

        btn_confirmar2.setBackground(new java.awt.Color(38, 53, 99));
        btn_confirmar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_confirmar2.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirmar2.setText("salvar alateração");
        btn_confirmar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_confirmar2);
        btn_confirmar2.setBounds(310, 270, 240, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nome\n");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 60, 37, 16);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Fornecedor\n");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 120, 70, 16);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Preço");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(60, 180, 37, 16);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Tarja");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(320, 60, 30, 16);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Peso Líquido");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(320, 120, 80, 16);

        Tipo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tipo2.setForeground(new java.awt.Color(0, 0, 0));
        Tipo2.setText("Tipo");
        jPanel1.add(Tipo2);
        Tipo2.setBounds(320, 180, 30, 16);

        comboEditMedcTipo.setBackground(new java.awt.Color(224, 229, 243));
        comboEditMedcTipo.setForeground(new java.awt.Color(0, 0, 0));
        comboEditMedcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comprimido", "Gota" }));
        comboEditMedcTipo.setBorder(null);
        jPanel1.add(comboEditMedcTipo);
        comboEditMedcTipo.setBounds(360, 170, 180, 30);

        comboEditMedcForn.setBackground(new java.awt.Color(224, 229, 243));
        comboEditMedcForn.setForeground(new java.awt.Color(0, 0, 0));
        comboEditMedcForn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "Vermelha", "Preta" }));
        comboEditMedcForn.setBorder(null);
        jPanel1.add(comboEditMedcForn);
        comboEditMedcForn.setBounds(120, 110, 160, 30);

        txtEditMedcPreco.setBackground(new java.awt.Color(224, 229, 243));
        txtEditMedcPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txtEditMedcPreco.setCaretColor(new java.awt.Color(38, 53, 99));
        txtEditMedcPreco.setSelectionColor(new java.awt.Color(38, 53, 99));
        txtEditMedcPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditMedcPrecoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEditMedcPreco);
        txtEditMedcPreco.setBounds(100, 170, 170, 30);

        txtEditMedcNome.setEditable(false);
        txtEditMedcNome.setBackground(new java.awt.Color(224, 229, 243));
        txtEditMedcNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txtEditMedcNome.setCaretColor(new java.awt.Color(38, 53, 99));
        txtEditMedcNome.setSelectionColor(new java.awt.Color(38, 53, 99));
        txtEditMedcNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditMedcNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtEditMedcNome);
        txtEditMedcNome.setBounds(100, 50, 180, 30);

        txtEditMedcPeso.setBackground(new java.awt.Color(224, 229, 243));
        txtEditMedcPeso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txtEditMedcPeso.setCaretColor(new java.awt.Color(38, 53, 99));
        txtEditMedcPeso.setSelectionColor(new java.awt.Color(38, 53, 99));
        txtEditMedcPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditMedcPesoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEditMedcPeso);
        txtEditMedcPeso.setBounds(400, 110, 140, 30);

        comboEditMedcTarja.setBackground(new java.awt.Color(224, 229, 243));
        comboEditMedcTarja.setForeground(new java.awt.Color(0, 0, 0));
        comboEditMedcTarja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "Vermelha", "Preta" }));
        comboEditMedcTarja.setBorder(null);
        jPanel1.add(comboEditMedcTarja);
        comboEditMedcTarja.setBounds(380, 50, 160, 30);

        txtEditMedcQtd.setBackground(new java.awt.Color(224, 229, 243));
        txtEditMedcQtd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txtEditMedcQtd.setCaretColor(new java.awt.Color(38, 53, 99));
        txtEditMedcQtd.setSelectionColor(new java.awt.Color(38, 53, 99));
        txtEditMedcQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditMedcQtdActionPerformed(evt);
            }
        });
        jPanel1.add(txtEditMedcQtd);
        txtEditMedcQtd.setBounds(140, 220, 130, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Quantidade");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(60, 230, 80, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(601, 353));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEditMedcPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditMedcPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditMedcPrecoActionPerformed

    private void txtEditMedcNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditMedcNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditMedcNomeActionPerformed

    private void txtEditMedcPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditMedcPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditMedcPesoActionPerformed

    private void txtEditMedcQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditMedcQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditMedcQtdActionPerformed
    
    private boolean validarCampos() {
        if(txtEditMedcNome.getText().length() > 0 && txtEditMedcPeso.getText().length() > 0 && txtEditMedcPreco.getText().length() > 0 && txtEditMedcQtd.getText().length() > 0) {
            return true;
        }
        return false;
    }
    
    private void bntApagarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntApagarMedicamentoActionPerformed
        this.conectar.conectaBanco();
        try {
            this.conectar.updateSQL("delete from medicamentos where nome = "+"'"+txtEditMedcNome.getText()+"';");
            JOptionPane.showMessageDialog (null, "Medicamentos apagado do banco de dados", "Apagado", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error",
            "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        } finally {
            this.conectar.fechaBanco();
        }      
    }//GEN-LAST:event_bntApagarMedicamentoActionPerformed

    private void btn_confirmar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmar2ActionPerformed
        this.conectar.conectaBanco();
        
        if(!validarCampos()) {
            JOptionPane.showMessageDialog(null, "Verifique os dados digitados",
            "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        else {
            try {
                Medicamentos novoMedicamento = new Medicamentos();
                novoMedicamento.setNome(txtEditMedcNome.getText());
                novoMedicamento.setTarja(comboEditMedcTarja.getSelectedItem().toString());
                novoMedicamento.setPreco(Float.parseFloat(txtEditMedcPreco.getText()));
                novoMedicamento.setPeso(Integer.parseInt(txtEditMedcPeso.getText()));
                novoMedicamento.setTipo(comboEditMedcTipo.getSelectedItem().toString());
                novoMedicamento.setQtd_estoque(Integer.parseInt(txtEditMedcQtd.getText()));
                novoMedicamento.setFornecedorId(comboEditMedcForn.getSelectedIndex() + 1);
                
                this.conectar.updateSQL("UPDATE medicamentos SET  nome ="+"'"+novoMedicamento.getNome()+"'"
                        +", tarja ="+"'"+novoMedicamento.getTarja()+"'"+", preco = "+"'"+novoMedicamento.getPreco()+"'"+", peso_liquido ="+"'"+novoMedicamento.getPeso()+"'"+", tipo ="+"'"+novoMedicamento.getTipo()+"'"+", qtd_estoque ="+"'"+novoMedicamento.getQtd_estoque()+"'"+ ", forncedor_id ="+"'"+novoMedicamento.getFornecedorId()+"'"+" where nome = "+"'"+novoMedicamento.getNome()+"'"+";");
                JOptionPane.showMessageDialog (null, "Editado", " editado do banco de dados", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error",
                "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
                System.out.println(e);
            } finally {
                this.conectar.fechaBanco();
            }
        }
    }//GEN-LAST:event_btn_confirmar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoRemedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoRemedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoRemedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoRemedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadoRemedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tipo2;
    private javax.swing.JButton bntApagarMedicamento;
    private javax.swing.JButton btn_confirmar2;
    private javax.swing.JComboBox<String> comboEditMedcForn;
    private javax.swing.JComboBox<String> comboEditMedcTarja;
    private javax.swing.JComboBox<String> comboEditMedcTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEditMedcNome;
    private javax.swing.JTextField txtEditMedcPeso;
    private javax.swing.JTextField txtEditMedcPreco;
    private javax.swing.JTextField txtEditMedcQtd;
    // End of variables declaration//GEN-END:variables
}
