/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fabrica.de.projetos;

import conexao.MySQL;
import javax.swing.JOptionPane;
import objetos.Fornecedor;

/**
 *
 * @author gabri
 */
public class ResultadoFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form ResultadoFornecedo
     */
    public ResultadoFornecedor() {
        initComponents();
    }
    
    MySQL conectar = new MySQL("localhost:3306","DataFarmaBanco","root","123mudar");
    
    public void setCampos(Fornecedor novoFornecedor) {
        txtEditFornNome.setText(novoFornecedor.getNome());
        txtEditFornTelefone.setText(novoFornecedor.getTelefone());
        txtEditFornEmail.setText(novoFornecedor.getEmail());
        txtEditFornCnpj.setText(novoFornecedor.getCnpj());
        txtEditFornCep.setText(novoFornecedor.getCep());
        txtEditFornEndereco.setText(novoFornecedor.getEndereco());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEditFornNome = new javax.swing.JTextField();
        txtEditFornTelefone = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtEditFornEmail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtEditFornEndereco = new javax.swing.JTextField();
        txtEditFornCep = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtEditFornCnpj = new javax.swing.JTextField();
        btnSalvarEditForn = new javax.swing.JButton();
        btnApagarForn = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Resultado");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 100, 28);

        txtEditFornNome.setEditable(false);
        txtEditFornNome.setBackground(new java.awt.Color(224, 229, 243));
        txtEditFornNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txtEditFornNome.setCaretColor(new java.awt.Color(38, 53, 99));
        txtEditFornNome.setSelectionColor(new java.awt.Color(38, 53, 99));
        txtEditFornNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditFornNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtEditFornNome);
        txtEditFornNome.setBounds(90, 60, 180, 30);

        txtEditFornTelefone.setBackground(new java.awt.Color(224, 229, 243));
        txtEditFornTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txtEditFornTelefone.setCaretColor(new java.awt.Color(38, 53, 99));
        txtEditFornTelefone.setSelectionColor(new java.awt.Color(38, 53, 99));
        txtEditFornTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditFornTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtEditFornTelefone);
        txtEditFornTelefone.setBounds(100, 110, 170, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Telefone ");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(40, 120, 60, 16);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nome\n");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 70, 37, 16);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Email");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(40, 170, 37, 16);

        txtEditFornEmail.setBackground(new java.awt.Color(224, 229, 243));
        txtEditFornEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txtEditFornEmail.setCaretColor(new java.awt.Color(38, 53, 99));
        txtEditFornEmail.setSelectionColor(new java.awt.Color(38, 53, 99));
        txtEditFornEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditFornEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEditFornEmail);
        txtEditFornEmail.setBounds(80, 160, 190, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Endereco");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(310, 170, 60, 16);

        txtEditFornEndereco.setBackground(new java.awt.Color(224, 229, 243));
        txtEditFornEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txtEditFornEndereco.setCaretColor(new java.awt.Color(38, 53, 99));
        txtEditFornEndereco.setSelectionColor(new java.awt.Color(38, 53, 99));
        txtEditFornEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditFornEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEditFornEndereco);
        txtEditFornEndereco.setBounds(370, 160, 190, 30);

        txtEditFornCep.setBackground(new java.awt.Color(224, 229, 243));
        txtEditFornCep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txtEditFornCep.setCaretColor(new java.awt.Color(38, 53, 99));
        txtEditFornCep.setSelectionColor(new java.awt.Color(38, 53, 99));
        txtEditFornCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditFornCepActionPerformed(evt);
            }
        });
        jPanel1.add(txtEditFornCep);
        txtEditFornCep.setBounds(370, 110, 190, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Cep");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(310, 120, 60, 16);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Cnpj");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(310, 70, 37, 16);

        txtEditFornCnpj.setEditable(false);
        txtEditFornCnpj.setBackground(new java.awt.Color(224, 229, 243));
        txtEditFornCnpj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txtEditFornCnpj.setCaretColor(new java.awt.Color(38, 53, 99));
        txtEditFornCnpj.setSelectionColor(new java.awt.Color(38, 53, 99));
        txtEditFornCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditFornCnpjActionPerformed(evt);
            }
        });
        jPanel1.add(txtEditFornCnpj);
        txtEditFornCnpj.setBounds(370, 60, 190, 30);

        btnSalvarEditForn.setBackground(new java.awt.Color(38, 53, 99));
        btnSalvarEditForn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvarEditForn.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarEditForn.setText("salvar alateração");
        btnSalvarEditForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditFornActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvarEditForn);
        btnSalvarEditForn.setBounds(310, 210, 240, 30);

        btnApagarForn.setBackground(new java.awt.Color(255, 51, 51));
        btnApagarForn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApagarForn.setForeground(new java.awt.Color(255, 255, 255));
        btnApagarForn.setText("remover fornecedor");
        btnApagarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarFornActionPerformed(evt);
            }
        });
        jPanel1.add(btnApagarForn);
        btnApagarForn.setBounds(40, 210, 230, 30);

        jToggleButton1.setBackground(new java.awt.Color(255, 51, 51));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Fechar");
        jToggleButton1.setBorder(null);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(490, 0, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(616, 290));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
   private boolean validarDados() {
        if(
                txtEditFornNome.getText().length() > 0 
                && txtEditFornTelefone.getText().length() > 0 
                && txtEditFornEmail.getText().length() > 0 
                && txtEditFornCnpj.getText().length() > 0
                && txtEditFornEndereco.getText().length() > 0
                && txtEditFornCep.getText().length() > 0)
        { return true;}
        else {
            return false;
        }
    }
    
    private void txtEditFornNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditFornNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditFornNomeActionPerformed

    private void txtEditFornTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditFornTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditFornTelefoneActionPerformed

    private void txtEditFornEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditFornEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditFornEmailActionPerformed

    private void txtEditFornEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditFornEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditFornEnderecoActionPerformed

    private void txtEditFornCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditFornCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditFornCepActionPerformed

    private void txtEditFornCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditFornCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditFornCnpjActionPerformed

    private void btnSalvarEditFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditFornActionPerformed
        this.conectar.conectaBanco();
        
        if(!this.validarDados()) {
            JOptionPane.showMessageDialog(null, "Verifique os dados digitados",
            "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else {
             try {
                this.conectar.updateSQL("UPDATE fornecedores SET  nome ="+"'"+txtEditFornNome.getText()+"'"+", telefone ="+"'"+txtEditFornTelefone.getText()+"'"+", email = "+"'"+txtEditFornEmail.getText()+"'"+", endereco ="+"'"+txtEditFornEndereco.getText()+"'"+", cep ="+"'"+txtEditFornCep.getText()+"'"+"where cnpj = "+"'"+txtEditFornCnpj.getText()+"';");
                JOptionPane.showMessageDialog (null, "Editado", " editado do banco de dados", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error",
                "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
                System.out.println(e);
            } finally {
                 this.conectar.fechaBanco();
            }
        }
    }//GEN-LAST:event_btnSalvarEditFornActionPerformed

    private void btnApagarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarFornActionPerformed
        this.conectar.conectaBanco();
        
        try {
            this.conectar.updateSQL("delete from fornecedores where cnpj = "+"'"+txtEditFornCnpj.getText()+"';");
            JOptionPane.showMessageDialog (null, "Fornecedor apagado do banco de dados", "Apagado", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error",
            "Verifique os dados digitados", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        } finally {
            this.conectar.fechaBanco();
        }
    }//GEN-LAST:event_btnApagarFornActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadoFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarForn;
    private javax.swing.JButton btnSalvarEditForn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtEditFornCep;
    private javax.swing.JTextField txtEditFornCnpj;
    private javax.swing.JTextField txtEditFornEmail;
    private javax.swing.JTextField txtEditFornEndereco;
    private javax.swing.JTextField txtEditFornNome;
    private javax.swing.JTextField txtEditFornTelefone;
    // End of variables declaration//GEN-END:variables
}
