/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fabrica.de.projetos;

import java.util.InputMismatchException;
import conexao.MySQL;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import objetos.Funcionario;
import javax.swing.JOptionPane;
/**
 *
 * @author koury
 */
public class TelaLogin extends javax.swing.JFrame {
    MySQL conectar = new MySQL("localhost:3306","DataFarmaBanco","root","123mudar");
    
    MenuTela menuTela = new MenuTela();
    Border borderError = BorderFactory.createLineBorder(Color.red,2);
        
    Funcionario funcionario = new Funcionario();
    
    public TelaLogin() {
        initComponents();
        txt_error_login.setVisible(false);
    }
    
    public static boolean isCPF(String CPF) {
        
        if (CPF.equals("00000000000") ||
            CPF.equals("11111111111") ||
            CPF.equals("22222222222") || CPF.equals("33333333333") ||
            CPF.equals("44444444444") || CPF.equals("55555555555") ||
            CPF.equals("66666666666") || CPF.equals("77777777777") ||
            CPF.equals("88888888888") || CPF.equals("99999999999") ||
            (CPF.length() != 11))
            return(false);

        char dig10, dig11;
        int sm, i, r, num, peso;

        
        try {
        
            sm = 0;
            peso = 10;
            for (i=0; i<9; i++) {
        
            num = (int)(CPF.charAt(i) - 48);
            sm = sm + (num * peso);
            peso = peso - 1;
            }

            r = 11 - (sm % 11);
            if ((r == 10) || (r == 11))
                dig10 = '0';
            else dig10 = (char)(r + 48); 

        
            sm = 0;
            peso = 11;
            for(i=0; i<10; i++) {
            num = (int)(CPF.charAt(i) - 48);
            sm = sm + (num * peso);
            peso = peso - 1;
            }

            r = 11 - (sm % 11);
            if ((r == 10) || (r == 11))
                 dig11 = '0';
            else dig11 = (char)(r + 48);

       
            if ((dig10 == CPF.charAt(9)) && (dig11 == CPF.charAt(10)))
                 return(true);
            else return(false);
                } catch (InputMismatchException erro) {
                return(false);
            }
        }
    
    
    private boolean validateFields() {
        boolean validate = this.isCPF(txt_cpf.getText());
        if(!validate && txt_password.getText() == "") {
            txt_cpf.setBorder(borderError);
            txt_error_login.setVisible(true);
            return false;
        }
        
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_logo_comp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_cpf = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        btn_confirmar = new javax.swing.JButton();
        lbl_bemvindo = new javax.swing.JLabel();
        lbl_info2 = new javax.swing.JLabel();
        lbl_info1 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_error_login = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(38, 53, 99));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabrica/de/projetos/img/logo datafarma 2.png"))); // NOI18N

        lbl_logo_comp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_logo_comp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logo_comp.setText("Tecnologia em Farmácia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_logo_comp)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_logo)
                        .addGap(138, 138, 138))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(lbl_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_logo_comp)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(460, 0, 457, 580);

        jPanel2.setBackground(new java.awt.Color(255, 250, 250));

        lbl_cpf.setText("CPF: ");

        lbl_senha.setText("Senha:");

        btn_confirmar.setBackground(new java.awt.Color(38, 53, 99));
        btn_confirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_confirmar.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirmar.setText("confirmar");
        btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmarActionPerformed(evt);
            }
        });

        lbl_bemvindo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_bemvindo.setText("Seja Bem Vindo!");

        lbl_info2.setForeground(new java.awt.Color(102, 102, 102));
        lbl_info2.setText("preencha os campos abaixo:");

        lbl_info1.setForeground(new java.awt.Color(102, 102, 102));
        lbl_info1.setText("Bem vindo, por favor,");

        txt_cpf.setBackground(new java.awt.Color(224, 229, 243));
        txt_cpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 229, 243), 2));
        txt_cpf.setCaretColor(new java.awt.Color(38, 53, 99));
        txt_cpf.setSelectionColor(new java.awt.Color(38, 53, 99));
        txt_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpfActionPerformed(evt);
            }
        });

        jLabel2.setText("se");

        txt_error_login.setForeground(new java.awt.Color(255, 0, 51));
        txt_error_login.setText("cpf ou senha inválidos");

        txt_password.setBackground(new java.awt.Color(224, 229, 243));
        txt_password.setBorder(null);
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_info1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_info2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bemvindo)
                    .addComponent(lbl_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_error_login)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_password, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_confirmar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(lbl_bemvindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_info1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_info2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_error_login)
                .addGap(30, 30, 30)
                .addComponent(lbl_cpf)
                .addGap(7, 7, 7)
                .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btn_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 457, 550);

        setSize(new java.awt.Dimension(929, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpfActionPerformed

    }//GEN-LAST:event_txt_cpfActionPerformed
    
    
    public String getUserId() {
        return funcionario.getId();
    }
    
    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
       this.conectar.conectaBanco();
       
        try {
            this.conectar.executarSQL(
            "SELECT "
                    +" id,"
                    + "nome,"
                    + "data_nasc,"
                    + "cpf,"
                    + "cargo,"
                    + "salario,"
                    + "senha"
                + " FROM "
                        + "funcionarios"
                + " WHERE "
                        + "cpf = "+"'"+txt_cpf.getText()+"';"
            );
            while (this.conectar.getResultSet().next()) {
                funcionario.setId(this.conectar.getResultSet().getString(1));
                funcionario.setNome(this.conectar.getResultSet().getString(2));
                funcionario.setData_nasc(this.conectar.getResultSet().getString(3));
                funcionario.setCpf(this.conectar.getResultSet().getString(4));
                funcionario.setCargo(this.conectar.getResultSet().getString(5));
                funcionario.setSalario(this.conectar.getResultSet().getString(6));
                funcionario.setSenha(this.conectar.getResultSet().getString(7));
            }
            
            if(funcionario.getCpf() == null) {
                txt_password.setBorder(borderError);
                txt_cpf.setBorder(borderError);
                txt_error_login.setVisible(true);
                txt_cpf.setText("");
                txt_password.setText("");
                System.out.println("werwrwrwrwer");
            }
            
            else {
                new VenderTela().funcionario_id = funcionario.getId();
                menuTela.setVisible(true);
                this.setVisible(false);
            }
        } catch (Exception e) {
        } finally {
            this.conectar.fechaBanco();
        }
    }//GEN-LAST:event_btn_confirmarActionPerformed

    
    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_bemvindo;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_info1;
    private javax.swing.JLabel lbl_info2;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_logo_comp;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JLabel txt_error_login;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
